services:
  mongodb:
    image: mongo:latest
    container_name: ctf_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: ctf_app
    ports:
      - "3010:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/jwt_ctf
      - JWT_SECRET=secret123
      - FLAG=FLAG{jwt_role_escalation_success}
    depends_on:
      - mongodb

volumes:
  mongo_data:
